name: Daily Commit

on:
  schedule:
    - cron: '46 18 * * *'   # Runs daily at 12:16 AM IST (6:46 PM UTC)
  workflow_dispatch:         # Optional: allows manual runs for testing

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update daily.txt with timestamp (24f1001182@ds.study.iitm.ac.in)
        run: echo "Last run: $(date -u)" > daily.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily.txt
          git commit -m "Daily commit: $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
